Fix ADB/MTP detection & adds another needed partitions to backup-restore lists
polygraphene/android_device_lenovo_TB320FC pull request #1
Opened 2024-11-17 10:17 UTC by lddnsk

1. I Fix ADB/MTP detection in the Windows. In your version device detected as unknown. I used another config and vendor&product IDs. Now all functions worked properly with Motorola drivers.
2. I added more partitions to backup-restore lists such as vendor_boot, frp, oemowninfo, efs, modem, recovery. This is needed on some cases.
3. I use device id "Lenovo_TB320FC instead of "serialno" for backup folder ( /sdcard/TWRP/BACKUPS/serialno/ --> /sdcard/TWRP/BACKUPS/Lenovo_TB320FC/ ).

2024-11-17 15:44 UTC, polygraphene commented
Thanks for sending the pull request. However, it looks like it needs a little cleanup before merge.
Your commits include many unrelated changes.

1.
The device is properly detected on my Windows PC. Did you install the usb driver in android sdk? The driver should work.

I defined mtp,adb mode as 0x18D1:0x4EE2. It is included in google's driver.
`(android-sdk)\extras\google\usb_driver\android_winusb.inf`
```
;Google Nexus (generic)
...
%CompositeAdbInterface%     = USB_Install, USB\VID_18D1&PID_4EE2&MI_01
```

See the following links for the installation instruction.
https://developer.android.com/studio/run/win-usb
https://developer.android.com/studio/run/oem-usb#InstallingDriver

Also, idVendor is already set by the following line. Not neccessary to reset on the init.recovery.usb.rc.
https://github.com/TeamWin/android_bootable_recovery/blob/a28a9f3867483fb5026601d954a3bf9059886b71/etc/init.rc#L130

For 2. and 3.:
Thanks. I didn't think much about paritions or serialno. I can merge it after clean up the commits.

2024-11-17 15:48 UTC, polygraphene requested changes
Unneccessary commit. Please exclude it.

2024-11-17 15:51 UTC, polygraphene reviewed
Only delete an empty line? Seems like unnecessary commit.

2024-11-17 15:54 UTC, polygraphene reviewed
It removes proper markdown paragraph. Unnecessary change.

2024-11-17 15:55 UTC, polygraphene reviewed
This change is for your repository. Not suitable for my repo.

2024-11-17 15:56 UTC, lddnsk commented
I am so sorry for superfluous moment. Just I don't know how pull partial changes request.
This is my first attempt to work with git. Not all my actions is right method.

2024-11-17 16:00 UTC, polygraphene reviewed
Many unrelated changes. A necessary part should be just 2-3 lines.

2024-11-17 16:00 UTC, polygraphene reviewed
Not necessary for my repo.

2024-11-17 16:02 UTC, lddnsk commented
> Google Nexus (generic)

Yes. device detected as Nexus. and ADB was dn`t work. And MTP device detected as some COM port or similar...
I don`t think is right idea use another device config. I use similar config from stock and it fully works. But if you think I mistaked - may be is it )

2024-11-17 16:05 UTC, lddnsk commented on BoardConfig.mk
> +TW_MTP_DEVICE := /dev/usb-ffs/mtp
This

2024-11-17 16:16 UTC, polygraphene commented
> I am so sorry for superfluous moment. Just I don't know how pull partial changes request.

It would be easier to create a new branch and copy only necessary changes.
Create a branch on your repo for my latest change. And copy required parts from this PR.

> This is my first attempt to work with git. Not all my actions is right method.

It's okay. If you have any questions, please feel free to ask.

2024-11-17 16:18 UTC, polygraphene commented
> > Google Nexus (generic)
> 
> Yes. device detected as Nexus. and ADB was dn't work. And MTP device detected as some COM port or similar... I don't think is right idea use another device config. I use similar config from stock and it fully works. But if you think I mistaked - may be is it )

Okay. My PC might have many unnecessary drivers. I will test on cleanly installed windows.

2024-11-17 17:30 UTC, polygraphene commented
Worked without problem on cleanly installed Win11 24H2. I didn't install google's driver.

![image](https://github.com/user-attachments/assets/a0586dd5-f3b9-441f-9a9f-83fd55340763)
![image](https://github.com/user-attachments/assets/e7ea0879-5cf3-4b2b-8889-337a092c674d)
![image](https://github.com/user-attachments/assets/274beb09-feab-4df5-a8c8-c2828fc5e6d4)

2024-11-18 04:09 UTC, lddnsk commented
> Worked without problem on cleanly installed Win11 24H2. I didn't install google's driver.

I cannot check now on clean windows but I have installed stock lenovo/moto drivers. I think if device don't work WITH OFFICIAL drivers this is not normally.
Another computer worked with your version.

ADB no device and no portable device at all
![adb](https://github.com/user-attachments/assets/4c4af25d-d030-4131-8097-d869434644e7)
fastbootD no device
![fastbootd](https://github.com/user-attachments/assets/5771953e-4cd3-46a1-ad90-6f0f88ed3db8)
Only if I turn off MTP then ADB device detected
![no MTP](https://github.com/user-attachments/assets/004f0ae9-e098-44d5-aba0-8f51ebf4972b)

My config:
![my](https://github.com/user-attachments/assets/9a0b813a-26e9-4c4f-a95e-3e1b37ca1d61)
![my_fastbootd](https://github.com/user-attachments/assets/3932d3bc-103b-44d3-afff-0316497e7105)

But another comp ADB no work in mode ADB+MTP .

I don't know how is better. I will more testing and at this moment I thinking my pull request slapdashed. I'l be back later, thank you for your answers  :)

2024-11-18 17:40 UTC, polygraphene commented
Thank you for testing. The device seems to be detected by another driver than google or lenovo's one in your PC.

Check what driver is 

Double click `Google Nexus Adb Interface` then open `Event` tab.
Look file name of `*.inf` file then find the file in `C:\Windows\INF`.

Open `*.inf` in text editor, then the file might have information about what driver is detecting the device.

In cleanly installed windows, the driver `winusb` from Microsoft can detect the device. And adb+MTP is working flawlessly.
![image](https://github.com/user-attachments/assets/41858890-0fcb-4662-bf1c-79fa06089388)
![image](https://github.com/user-attachments/assets/eb9f6d87-7c6c-4493-9457-c0ae4022ad21)

After installing Lenovo Software Fix, it is detected as `LeMobile Android Device`. And adb+MTP is still working.
![image](https://github.com/user-attachments/assets/600889c8-ae8f-4028-a735-baad208a29e3)
![image](https://github.com/user-attachments/assets/a0ec0e0c-c327-4f6f-9eb1-c39bfaa34871)
![image](https://github.com/user-attachments/assets/3e699487-9fbb-42d3-a37a-eb5a840a9f51)

2024-11-18 17:46 UTC, polygraphene commented
I thought my config should work on any driver, but if your config (Lenovo's idProduct?) is working fine for broader environment than mine, I would prefer yours.
I want to clearify the difference of your config and mine. And I want to know the real cause of the issue before merging PR.

2024-11-22 04:26 UTC, closed without merging